[package]
name = "quipu-store"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "SignedObject genérico + trait ObjectStore para la red quipu"

[dependencies]
quipu-identity = { path = "../quipu-identity" }
blake3 = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
